In [1]:
import pandas as pd

In [2]:
merged_df = pd.read_csv('merged_data.csv')

In [3]:
merged_df.describe()

,Account.ID,Open.Count,Email.Retry.Count,Email.Link.Click.Count,Email.Template.ID,Email.Error.Code,Email.Final.Receipt,Invalid.Email.Address,Email.Address.Bounce.Count,X.x,Salutation,X.y
count,5701.000000,2217.000000,2484.0,276.000000,5701.000000,33.000000,0.0,0.0,41.000000,0.0,0.0,0.0
mean,1736.053499,3.930537,2.0,1.195652,231.903175,547.696970,NaN,NaN,1.292683,NaN,NaN,NaN
std,1120.249479,61.313773,0.0,0.860095,4.715308,17.232754,NaN,NaN,0.813754,NaN,NaN,NaN
min,8.000000,1.000000,2.0,1.000000,223.000000,452.000000,NaN,NaN,1.000000,NaN,NaN,NaN
25%,845.000000,1.000000,2.0,1.000000,227.000000,550.000000,NaN,NaN,1.000000,NaN,NaN,NaN
50%,1618.000000,1.000000,2.0,1.000000,236.000000,550.000000,NaN,NaN,1.000000,NaN,NaN,NaN
75%,2367.000000,2.000000,2.0,1.000000,236.000000,550.000000,NaN,NaN,1.000000,NaN,NaN,NaN
max,7099.000000,2760.000000,2.0,8.000000,236.000000,554.000000,NaN,NaN,5.000000,NaN,NaN,NaN

In [4]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5701 entries, 0 to 5700
Data columns (total 38 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Account.ID                     5701 non-null   int64
 1   Email.First.Open.Date          2217 non-null   object
 2   Email.Last.Open.Date           2217 non-null   object
 3   Open.Count                     2217 non-null   float64
 4   Email.Recipient.Full.Name..F.  5701 non-null   object
 5   Email                          5701 non-null   object
 6   Email.Retry.Count              2484 non-null   float64
 7   Email.Send.Date.Time           5701 non-null   object
 8   Email.Type                     5701 non-null   object
 9   Email.First.Click.Date         276 non-null    object
 10  Email.Last.Click.Date          276 non-null    object
 11  Email.Link.Click.Count         276 non-null    float64
 12  Email.Template.Name            5701 non-null   object
 13  Email.Link.Name                276 non-null    object
 14  Email.Template.ID              5701 non-null   int64
 15  Email.Address.Opt.Out.Date     184 non-null    object
 16  Email.Error.Code               33 non-null     float64
 17  Email.Error.Note               2 non-null      object
 18  Email.Receipt.Mail.Server      2 non-null      object
 19  Email.Final.Receipt            0 non-null      float64
 20  Email.Last.Attempt.Date        2 non-null      object
 21  Invalid.Email.Address          0 non-null      float64
 22  Email.Last.Modified.Date.Time  184 non-null    object
 23  Email.Address.Bounce.Count     41 non-null     float64
 24  Email.Address.Block.Type       184 non-null    object
 25  Email.Campaign.Name            5701 non-null   object
 26  Email.Address.Opt.Out          143 non-null    object
 27  X.x                            0 non-null      float64
 28  Account.Type                   5701 non-null   object
 29  Salutation                     0 non-null      float64
 30  Full.Name..F.                  5696 non-null   object
 31  Company.Name                   542 non-null    object
 32  Address.Line.1                 2406 non-null   object
 33  City                           2433 non-null   object
 34  State.Province                 2433 non-null   object
 35  Zip.Code                       5675 non-null   object
 36  Largest.Donation.Amount        5701 non-null   object
 37  X.y                            0 non-null      float64
dtypes: float64(10), int64(2), object(26)
memory usage: 1.7+ MB

In [7]:
merged_df['Largest.Donation.Amount'] = merged_df['Largest.Donation.Amount'].apply(lambda x: x.replace(',', ''))

In [8]:
merged_df = merged_df.astype({'Largest.Donation.Amount': 'float64'})

In [16]:
merged_df.drop(columns=['X.y', 'X.x', 'Invalid.Email.Address', 'Email.Final.Receipt', 'Salutation'], inplace=True)

KeyError: "['X.y', 'X.x', 'Invalid.Email.Address', 'Email.Final.Receipt'] not found in axis"

In [12]:
for col in merged_df.columns: 
    if 'date' in col.lower(): 
        merged_df[col] = pd.to_datetime(merged_df[col])

In [13]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5701 entries, 0 to 5700
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Account.ID                     5701 non-null   int64
 1   Email.First.Open.Date          2217 non-null   datetime64[ns]
 2   Email.Last.Open.Date           2217 non-null   datetime64[ns]
 3   Open.Count                     2217 non-null   float64
 4   Email.Recipient.Full.Name..F.  5701 non-null   object
 5   Email                          5701 non-null   object
 6   Email.Retry.Count              2484 non-null   float64
 7   Email.Send.Date.Time           5701 non-null   datetime64[ns]
 8   Email.Type                     5701 non-null   object
 9   Email.First.Click.Date         276 non-null    datetime64[ns]
 10  Email.Last.Click.Date          276 non-null    datetime64[ns]
 11  Email.Link.Click.Count         276 non-null    float64
 12  Email.Template.Name            5701 non-null   object
 13  Email.Link.Name                276 non-null    object
 14  Email.Template.ID              5701 non-null   int64
 15  Email.Address.Opt.Out.Date     184 non-null    datetime64[ns]
 16  Email.Error.Code               33 non-null     float64
 17  Email.Error.Note               2 non-null      object
 18  Email.Receipt.Mail.Server      2 non-null      object
 19  Email.Last.Attempt.Date        2 non-null      datetime64[ns]
 20  Email.Last.Modified.Date.Time  184 non-null    datetime64[ns]
 21  Email.Address.Bounce.Count     41 non-null     float64
 22  Email.Address.Block.Type       184 non-null    object
 23  Email.Campaign.Name            5701 non-null   object
 24  Email.Address.Opt.Out          143 non-null    object
 25  Account.Type                   5701 non-null   object
 26  Salutation                     0 non-null      float64
 27  Full.Name..F.                  5696 non-null   object
 28  Company.Name                   542 non-null    object
 29  Address.Line.1                 2406 non-null   object
 30  City                           2433 non-null   object
 31  State.Province                 2433 non-null   object
 32  Zip.Code                       5675 non-null   object
 33  Largest.Donation.Amount        5701 non-null   float64
dtypes: datetime64[ns](8), float64(7), int64(2), object(17)
memory usage: 1.5+ MB

In [15]:
merged_df.rename(columns={'Email.Recipient.Full.Name..F.': 'Email.Recipient.Full.Name', 'Address.Line.1': 'Address', 'Full.Name..F.': 'Full.Name'}, inplace=True)

In [18]:
merged_df.to_csv('cleaned_merged_df.csv')